# Generated by Django 4.2.9 on 2024-03-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(blank=1, max_length=2000, null=1)),
                ('to_user', models.CharField(blank=1, max_length=2000, null=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=1, max_length=2000, null=1)),
                ('message', models.CharField(blank=1, max_length=2000, null=1)),
                ('notification_type', models.CharField(choices=[('L', 'LIKED'), ('C', 'COMMENTED'), ('S', 'ALSO_COMMENTED'), ('F', 'FOLLOWED'), ('U', 'UNFOLLOWED'), ('U', 'REQUEST_FRIENDSHIPD'), ('U', 'ACCEPT_FRIENDSHIPD'), ('R', 'RESPONDED'), ('TEXTED', 'TEXTED')], max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_recomendation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(blank=1, max_length=2000, null=1)),
                ('to_user', models.CharField(blank=1, max_length=2000, null=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=1, max_length=2000, null=1)),
                ('message', models.CharField(blank=1, max_length=2000, null=1)),
                ('notification_type', models.CharField(choices=[('L', 'LIKED'), ('C', 'COMMENTED'), ('S', 'ALSO_COMMENTED'), ('F', 'FOLLOWED'), ('U', 'UNFOLLOWED'), ('U', 'REQUEST_FRIENDSHIPD'), ('U', 'ACCEPT_FRIENDSHIPD'), ('R', 'RESPONDED'), ('TEXTED', 'TEXTED')], max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_recomendation', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-date',),
            },
        ),
    ]
